apiVersion: v1
kind: Service
metadata:
  name:  auth-app-svc
  namespace: development
spec:
  selector:
    app:  auth-app
  type:  ClusterIP
  ports:
  - name: auth-svc-port
    port: 80
    targetPort: app-port